# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for Decodo MCP Server

FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package and TypeScript config files
COPY package.json package-lock.json tsconfig.json ./

# Copy source code and entrypoint
COPY src ./src

# Install dependencies and build
RUN npm install --ignore-scripts \
    && npm run build

# Run the MCP server via stdio
CMD ["node", "build/index.js"]
